Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Controllers/MyHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;


namespace Online_Boutique.Controllers
{
    
    public class MyHomeController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyHome
        public ActionResult Index()
        {
            var listnewsp = db.SanPhams.OrderBy(x=>x.ngaynhapsp).Take(12).ToList();
            return View(listnewsp);
        }

        public PartialViewResult HeaderPartial(string gt)
        {
            object listrecord;
            List<GioHang> ls = Session["cart"] as List<GioHang>;

               if(ls != null)
            {
                ViewBag.soluong = ls.Count;
                ViewBag.tongtien = ls.Sum(x => x.thanhtien);
            }
               else
            {
                ViewBag.soluong = 0;
                ViewBag.tongtien = 0;
            }
           // if (gt == "nu")

            listrecord = db.LoaiSanPhams.Where(x => x.gioitinh == "nữ").OrderBy(x => x.tenloaisp).ToList();
          //  else
            
           //      listrecord = db.LoaiSanPhams.Where(x => x.gioitinh == "nam").OrderBy(x => x.tenloaisp).ToList();
            
            return PartialView(listrecord);
               
            
        }

        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }
        public PartialViewResult ContainerPartial()
        {
            return PartialView(db.SanPhams.Take(8).ToList());
        }

    }
}

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/Shared/TrangChu_Layout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->


<!DOCTYPE html>
<html>
<head>
    <title>Eshop a Flat E-Commerce Bootstrap Responsive Website Template | Home :: w3layouts</title>
    <link href="~/Content/web/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Content/web/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <link href="~/Content/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Eshop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <!-- for bootstrap working -->
    <script type="text/javascript" src="~/Content/web/js/bootstrap-3.1.1.min.js"></script>
    <!-- //for bootstrap working -->
    <!-- cart -->
    <script src="~/Content/web/js/simpleCart.min.js"> </script>
    <!-- cart -->
    <link rel="stylesheet" href="~/Content/web/css/flexslider.css" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" href="~/Content/My_Online_Boutique.css" />
    
    <link href="~/public/css/style1.css" rel="stylesheet" type="text/css" />
    <link href="~/public/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

    <script src="~/public/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/public/js/lib.js"></script>
    <script type="text/javascript" src="~/public/js/bxslider.js"></script>
    <script src="~/public/js/range-slider.js"></script>
    <script src="~/public/js/jquery.zoom.js"></script>
    <script type="text/javascript" src="~/public/js/bookblock.js"></script>
    <script type="text/javascript" src="~/public/js/custom.js"></script>
    <script type="text/javascript" src="~/public/js/social.js"></script>
    <script src="~/public/js/formValidation.min1.js" type="text/javascript"></script>
    <script src="~/public/js/formValidation.min2.js" type="text/javascript"></script>
    <script src="~/public/js/index1.js" type="text/javascript"></script>
</head>
<body>

    <!-- header-section-va thanh menu starts -->
        
        @Html.Action("HeaderPartial","MyHome")   @*hoặc @Html.Action("HeaderPartial","MyHome")..nếu dùng @Html.Partial(..)là bị lỗi*@
  
    <!-- header-section-va thanh menu ends -->
    
    <div class="banner">
        <div class="container">
            <div class="banner-bottom">
                <div class="banner-bottom-left">
                    <h2>B<br>U<br>Y</h2>
                </div>
                <div class="banner-bottom-right">
                    <div class="callbacks_container">
                        <ul class="rslides" id="slider4">
                            <li>
                                <div class="banner-info">
                                    <h3>Smart But Casual</h3>
                                    <p>Start your shopping here...</p>
                                </div>
                            </li>
                            <li>
                                <div class="banner-info">
                                    <h3>Shop Online</h3>
                                    <p>Start your shopping here...</p>
                                </div>
                            </li>
                            <li>
                                <div class="banner-info">
                                    <h3>Pack your Bag</h3>
                                    <p>Start your shopping here...</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!--banner-->
                    <script src="~/Content/web/js/responsiveslides.min.js"></script>
                    <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager:true,
			        nav:false,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });

			    });
                    </script>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="shop">
                <a href="single.html">SHOP COLLECTION NOW</a>
            </div>
        </div>
    </div>
    <!-- content-section-starts-here -->
    @RenderBody()

        @Html.Action("ContainerPartial")
    <!-- content-section-ends-here -->
    
    @Html.Action("FooterPartial","MyHome")
</body>
</html>

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/Shared/TrangCon_Layout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Eshop a Flat E-Commerce Bootstrap Responsive Website Template | Products :: w3layouts</title>
<link href="~/Content/web/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="~/Content/web/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="~/Content/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/Content/web/css/component.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Eshop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<!-- for bootstrap working -->
	<script type="text/javascript" src="~/Content/web/js/bootstrap-3.1.1.min.js"></script>
<!-- //for bootstrap working -->
<!-- cart -->
	<script src="~/Content/web/js/simpleCart.min.js"> </script>
<!-- cart -->
<link rel="stylesheet" href="~/Content/web/css/flexslider.css" type="text/css" media="screen" />
<link rel="stylesheet" href="~/Content/My_Online_Boutique.css" type="text/css" />
    
    <link href="~/public/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
   
 
    <link href="~/public/css/style1.css" rel="stylesheet" type="text/css" />
    <script src="~/public/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/public/js/lib.js"></script>
    <script type="text/javascript" src="~/public/js/bxslider.js"></script>
    <script src="~/public/js/range-slider.js"></script>
    <script src="~/public/js/jquery.zoom.js"></script>
    <script type="text/javascript" src="~/public/js/bookblock.js"></script>
    <script type="text/javascript" src="~/public/js/custom.js"></script>
    <script type="text/javascript" src="~/public/js/social.js"></script>
    <script src="~/public/js/formValidation.min1.js" type="text/javascript"></script>
    <script src="~/public/js/formValidation.min2.js" type="text/javascript"></script>
    <script src="~/public/js/index1.js" type="text/javascript"></script>
</head>
<body>
    @Html.Action("HeaderPartial", "MyHome")

            
    @RenderSection("leftcontent",required:true)
           
    @RenderBody()
        
    
    @Html.Action("FooterPartial", "MyHome")
</body>
</html>

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>