Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Controllers/MyManageProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;
using System.IO;

namespace Online_Boutique.Controllers
{
    public class MyManageProductsController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyManageProducts
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachSP()
        {
            return View(db.SanPhams.OrderBy(x=>x.tensp).ToList());
        }

        [HttpGet]
        public ActionResult ThemSP()
        {
            ViewBag.maloaisp = new SelectList(db.LoaiSanPhams.OrderBy(x => x.tenloaisp).ToList(), "maloaisp", "tenloaisp");
            return View();
        }

        [HttpPost]
        // post du lieu len,bao gom ca anh
        public ActionResult ThemSP(SanPham sp, HttpPostedFileBase hpfb)
        {
            ViewBag.maloaisp = new SelectList(db.LoaiSanPhams.OrderBy(x => x.tenloaisp).ToList(), "maloaisp", "tenloaisp");
            if(hpfb==null)
            {
                ViewBag.thongbao = "trường này là bắt buộc, chọn hình ảnh";
            }
            else
            {
                var filename = Path.GetFileName(hpfb.FileName);

                //lưu đường dẫn của file
                var path = Path.Combine(Server.MapPath("~/HinhAnh/Nu"), filename);

                //kiem tra hinh anh da ton tai chua
                if (System.IO.File.Exists(path))
                {
                    ViewBag.thongbao = "hình ảnh đã tồn tại";
                }
                if (ModelState.IsValid)  //thoa man cac validation
                {
                    hpfb.SaveAs(path);  //luu vao folder o visualstudio
                    sp.anhsp = hpfb.FileName;

                    db.SanPhams.Add(sp);
                    db.SaveChanges();


                }
            }
          
            return View(); 
        }

        //chinh sua san pham
        [HttpGet]
        public ActionResult SuaSP(int masp=0)
        {
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.masp == masp);
            if (sp == null)
            {
              
                Response.StatusCode = 404;
                return null;
            }
            else
            {
                ViewBag.maloaisp = new SelectList(db.LoaiSanPhams.OrderBy(x => x.tenloaisp).ToList(), "maloaisp", "tenloaisp",sp.maloaisp);
                return View(sp);
            }
        }

        [HttpPost]
        public ActionResult SuaSP(SanPham sp)
        {
            ViewBag.maloaisp = new SelectList(db.LoaiSanPhams.OrderBy(x => x.tenloaisp).ToList(), "maloaisp", "tenloaisp", sp.maloaisp);
            if (ModelState.IsValid)
            {

                db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
                return View();
            
            //Cach2
            //    SanPham sp1 = db.SanPhams.SingleOrDefault(x => x.masp = sp.masp);
            //    sp1.cacthuoctinh = sp.cacthuoctinh tương ứng
            //    db.SaveChanges();
        }
      
        [HttpGet]
        public ActionResult XoaSP(int masp)
        {
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.masp == masp);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            else
                return View(sp);
        }

        [HttpPost]
        public ActionResult XoaSP(SanPham sp)
        {

            db.Entry(sp).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges(); ;
            return RedirectToAction("DanhSachSP");
        }
    }
}

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/MyManageProducts/DanhSachSP.cshtml
@model IEnumerable<Online_Boutique.Models.MyModels.SanPham>

@{
    ViewBag.Title = "DanhSachSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh Sách Sản Phẩm</h2>

<p>
    @Html.ActionLink("Thêm Sản Phẩm", "ThemSP")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.masp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tensp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giagocsp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.maloaisp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giabansp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ngaynhapsp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.soluongsp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.motasp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.anhsp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tinhtrangsp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.size)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.masp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tensp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.giagocsp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSanPham.tenloaisp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.giabansp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ngaynhapsp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.soluongsp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.motasp)
        </td>
        <td>
            <img src="@Url.Content("~/HinhAnh/nu/"+@item.anhsp)" class="anhsp" style="height:150px;width:120px;"alt="" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tinhtrangsp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.size)
        </td>
        <td>
            @Html.ActionLink("Chỉnh Sửa", "SuaSP", new {@masp=@item.masp }) |
            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
            @Html.ActionLink("Xóa", "XoaSP", new { @masp= @item.masp })
        </td>
    </tr>
}

</table>

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/MyManageProducts/SuaSP.cshtml
@model Online_Boutique.Models.MyModels.SanPham

@{
    ViewBag.Title = "SuaSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thay Đổi Thông Tin Sản Phẩm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sản Phẩm: @Model.masp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.masp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.masp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.masp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giagocsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giagocsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giagocsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maloaisp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.maloaisp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maloaisp, "", new { @class = "text-danger" })*@

                @Html.DropDownList("maloaisp")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giabansp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giabansp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giabansp, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ngaynhapsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaynhapsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaynhapsp, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.soluongsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongsp, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motasp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.motasp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.motasp, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.anhsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.anhsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.anhsp, "", new { @class = "text-danger" })

                @*<img src="@Url.Content("~/HinhAnh/Nu/"+Model.anhsp)" class="anhsp" style="height:150px;width:120px;" alt="" />
                tại sao cứ chèn thêm cái này thì bấm lưu thay đổi lại bị lỗi....vì nó nằm trong @Html.BeginForm(){ }?????*@
            </div>
            
        </div>
        
       

        <div class="form-group">
            @Html.LabelFor(model => model.tinhtrangsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tinhtrangsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tinhtrangsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu Thay Đổi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về Danh Sách", "DanhSachSP")
</div>

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/MyManageProducts/ThemSP.cshtml
@model Online_Boutique.Models.MyModels.SanPham

@{
    ViewBag.Title = "ThemSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm Sản Phẩm</h2>        @*Native SQL EF....LinQ....do la 2 cach truy van du lieu*@

@*thêm thuộc tính cho form để upload ảnh....hình như nếu ko upload ảnh thì 2 tham số đầu là mặc định*@
@using (Html.BeginForm("ThemSP","MyManageProducts",FormMethod.Post, new { @enctype="multipart/form-data"}))
// no giong nhu the form thôi...vd @Html.Actionlink thi no giống như thẻ a
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.masp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.masp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.masp, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giagocsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giagocsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giagocsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maloaisp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.maloaisp, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("maloaisp")
                @*@Html.ValidationMessageFor(model => model.maloaisp, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giabansp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giabansp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giabansp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaynhapsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaynhapsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaynhapsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluongsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motasp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.motasp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.motasp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.anhsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              @*  @Html.EditorFor(model => model.anhsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.anhsp, "", new { @class = "text-danger" }) *@
            <input type="file" name="hpfb" />
                @*ten cua the input nay phai trung voi tham so cua actionresult*@
            
            @ViewBag.thongbao

                @*???? neu no ko chay vao vong if do thi lam gi co viewbag.thongbao...the ko bi lỗi ak*@
            
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tinhtrangsp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tinhtrangsp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tinhtrangsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DanhSachSP")
</div>

Online_Boutique_2/Online_Boutique_2/Online_Boutique/Online_Boutique/Views/MyManageProducts/XoaSP.cshtml
@model Online_Boutique .Models.MyModels.SanPham

@{
    ViewBag.Title = "XoaSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Bạn có chắc chắn muốn xóa sản phẩm này?</h3>
<div>
    <h4>Sản Phẩm: @Model.masp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model =>@Model.masp)
        </dt>

        <dd>
            @Html.DisplayFor(model => @model.masp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giagocsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giagocsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maloaisp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.tenloaisp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giabansp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giabansp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaynhapsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaynhapsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.motasp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.motasp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.anhsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anhsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tinhtrangsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tinhtrangsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.size)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        
        <div class="form-actions no-color">
            <input type="submit" value="Xác Nhận Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở Về Danh Sách", "DanhSachSP")
        </div>
    }
</div>